# ===========================
# Netlify CMS
# https://www.netlifycms.org/docs/
# A full example https://github.com/netlify/netlify-cms/blob/master/dev-test/config.yml

display_url: https://digital.gov
site_url: https://digital.gov

# logo_url — sets the logo in the Workflow admin
# logo_url: https://digital.gov/img/digit-150.png
logo_url: https://digital.gov/logos/digitalgov-logo.png

# Backend and connections
backend:
  name: github
  repo: GSA/digitalgov.gov
  base_url: https://federalistapp.18f.gov
  auth_endpoint: external/auth/github
  preview_context: federalist/build
  open_authoring: true # accept contributions (forks) from GitHub users
  branch: master
  squash_merges: true # squash all commits into a single commit when the PR is merged
  commit_messages:
    create: 'New {{collection}}: "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: 'Upload "{{path}}"'
    deleteMedia: 'Delete "{{path}}"'
    openAuthoring: '{{message}}, {{author-login}}'


# Enables the NetlifyCMS editorial workflow tools
publish_mode: editorial_workflow


# MEDIA IS NOT BEING USED AT THIS TIME
# Media / Images
# This is where media will be stored in the repo
media_folder: "static/media"
# Path for uploaded media on the live site
public_folder: "/media"


# slug — sets how filenames for entries are created and sanitized.
slug:
  encoding: "unicode"
  clean_accents: true


# Localhost Editing
# uses the local proxy server port
# This is configured to run in our `npm start` script, defined in packages.json
local_backend:
  url: http://localhost:8081/api/v1



# ==============================================
# Content Collections
collections:



  # EVENTS =======================
  - name: "events" # Used in routes, e.g., /workflow/collections/blog
    label: "Events" # Used in the UI
    label_singular: 'Event'
    description: "TKTK"
    folder: "content/events" # path to the folder where files are stored
    path: '{{slug}}' # custom file path
    create: true # Allow users to create new documents in this collection
    identifier_field: title # sets the field that is used to create the slug
    slug: "{{slug}}"

    # =================================
    # Field Settings
    # - label     — the title that will appear above the field in the editor
    # - name      — this is the key that will be used in the front matter
    # - widget    — the type of field — See https://www.netlifycms.org/docs/widgets/ for all types
    # - required  — all fields are required by default unless you include `required: false`
    # - hint  — this is the helper text that occurrs below the field.
    # Available fields: https://www.netlifycms.org/docs/widgets/#markdown

    fields: # The fields for each document, usually in front matter

      - label: "Title"
        name: "title"
        widget: "string"
        hint: "Make it good!"

      - label: "Deck"
        name: "deck"
        widget: "string"
        hint: "TKTK"
        required: false

      - label: "Summary"
        name: "summary"
        widget: "string"
        hint: "TKTK"

      - label: "Registration URL"
        name: "registration_url"
        widget: "string"
        hint: "TKTK"
        required: false






  # AUTHORS =======================
  - name: "authors" # Used in routes, e.g., /workflow/collections/blog
    label: "Authors" # Used in the UI
    label_singular: 'Author'
    description: "TKTK"
    folder: "content/authors" # path to the folder where files are stored
    path: '{{slug}}/_index' # custom file path
    create: true # Allow users to create new documents in this collection
    identifier_field: display_name # sets the field that is used to create the slug
    slug: "{{slug}}"

    # =================================
    # Field Settings
    # - label     — the title that will appear above the field in the editor
    # - name      — this is the key that will be used in the front matter
    # - widget    — the type of field — See https://www.netlifycms.org/docs/widgets/ for all types
    # - required  — all fields are required by default unless you include `required: false`
    # - hint  — this is the helper text that occurrs below the field.
    # Available fields: https://www.netlifycms.org/docs/widgets/#markdown

    fields: # The fields for each document, usually in front matter

      - label: "Display Name"
        name: "display_name"
        widget: "string"
        hint: "text below the field"

      - label: "First Name"
        name: "first_name"
        widget: "string"
        hint: "TKTK"

      - label: "Last Name"
        name: "last_name"
        widget: "string"
        hint: "TKTK"

      - label: "Pronoun"
        name: "pronoun"
        widget: "string"
        hint: "TKTK"
        required: false

      - label: "Email"
        name: "email"
        widget: "string"
        hint: "TKTK"
        required: false

      - label: "Bio"
        name: "bio"
        widget: "text"
        hint: "TKTK"
        minimal: true
        pattern: ['.{20,}', "Must have at least 20 characters"]
        required: false

      - label: "Bio URL"
        name: "bio_url"
        widget: "string"
        hint: "Provide a full URL to where people can learn more about your work."
        required: false

      - label: "Agency Full Name"
        name: "agency_full_name"
        widget: "string"
        hint: "e.g. U.S. General Services Administration"
        comment: "# Agency Full Name [e.g. U.S. General Services Administration]"
        required: false

      - label: "Agency Acronym"
        name: "agency"
        widget: "string"
        hint: "e.g. GSA"
        comment: "# Agency Acronym [e.g., GSA]"
        required: false

      - label: "Location"
        name: "location"
        widget: "string"
        hint: "Help us show that the federal workforce is not all in the D.C. area.<br/>Where in the country do you live in? [e.g. 'New York City' or 'Portland, OR']"
        required: false

      - label: "GitHub ID"
        name: "github"
        widget: "string"
        hint: "[e.g. 'jeremyzilar'] — We'll use your GitHub profile image as your author photo on Digital.gov"
        required: false

      - label: "Profile Photo"
        name: "profile_photo"
        widget: "select"
        options: ["github", "digit-light", "digit-dark", "digit-pride"]
        hint: "TKTK"
        required: false

      - label: "Twitter"
        name: "twitter"
        widget: "string"
        hint: "Enter your username without the @ handle [e.g. digital_gov]"
        required: false

      - label: "Facebook"
        name: "facebook"
        widget: "string"
        required: false

      - label: "Instagram"
        name: "instagram"
        widget: "string"
        required: false

      - label: "Linkedin"
        name: "linkedIn"
        widget: "string"
        required: false

      - label: "YouTube"
        name: "youtube"
        widget: "string"
        required: false
