env:
  browser: true
  es2021: true
  node: true
extends:
  - airbnb-base
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
rules:
  prettier/prettier: error
settings:
  import/resolver:
    node:
      extensions: ['.js', '.jsx', '.ts', '.tsx']
overrides:
  - files: ['*.js', '*.jsx']
    rules: 
      prettier/prettier: error
  - files: ['*.ts', '*.tsx']
    extends:
      - plugin:@typescript-eslint/recommended
    rules:
      prettier/prettier: error
      no-console: off  # This disables the console statement warning for TypeScript files
      consistent-return: off  # This disables the consistent return warning for TypeScript files
      '@typescript-eslint/no-explicit-any': off  # This disables the explicit any warning for TypeScript files
      'no-await-in-loop': off  # This disables the await in loop warning for TypeScript files
      'no-restricted-syntax': off  # This disables the restricted syntax warning for TypeScript files