---
###########################
###########################
## Markdown Linter rules ##
###########################
###########################

# Linter rules doc:
# - https://github.com/DavidAnson/markdownlint
#
# Note:
# To comment out a single error:
#   <!-- markdownlint-disable -->
#   any violations you want
#   <!-- markdownlint-restore -->
#

###############
# Rules by id #
###############
MD001: false # Header levels should only increment by one level at a time
MD004: false # Unordered list style
MD007:
  indent: 4 # Unordered list indentation
MD013: false # Line length
MD024: false # Multiple headers with the same content
MD026: false # Trailing punctuation in header
MD029: false # Ordered list item prefix
MD033: false # Allow inline HTML
MD034: false # Bare URL used
MD036: false # Emphasis used instead of a heading
MD040: false # Fenced code blocks should have a language specified
